version: '3.8'
services:
  node:
    container_name: docker-node
    restart: always
    build: node_API/
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'